apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.yaml: |
    server:
      port: 8080
    app:
      greeting: Different greeting
    logging:
      file:
        name: /app/logs/app-${HOSTNAME}.log
      level:
        root: info
