apiVersion: v1
kind: Pod
metadata:
  name: hw1
spec:
  containers:
    - name: hw1
      image: annstase/sbt_devops:3
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      args: ["--spring.config.location=file:/app/config/application.yaml"]
      volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
        - name: config-volume
          mountPath: /app/config
  volumes:
    - name: logs-volume
      emptyDir: {}
    - name: config-volume
      configMap:
        name: app-config
        items:
          - key: application.yaml
            path: application.yaml
